language: node_js
node_js:
  - '12'

install:
  - npm install

script:
  - mkdir dist
  - npm run build
  - sed -i dist/index.html -f gatracking.sed

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: dist/
  on:
    branch: master

branches:
  only:
    - master
